name: Rust Unit Tests

on:
  push:
    paths:
      - '2022/rust_03/**'
  pull_request:
    paths:
      - '2022/rust_03/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: '2022/rust_03'

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build
      run: cargo build --verbose

    - name: Run Unit Tests
      run: cargo test --verbose
